package waproto

import (
	"crypto/md5"
	"strconv"

	"google.golang.org/protobuf/proto"
)

// WAVersion is the WhatsApp Web client version triple, e.g. {2, 3000, 1035194821}.
// It is sent in the UserAgent and md5-hashed into devicePairingData.buildHash.
type WAVersion [3]uint32

// String renders the version as "primary.secondary.tertiary" — the exact form
// the Baileys client md5-hashes for the buildHash field.
func (v WAVersion) String() string {
	return strconv.FormatUint(uint64(v[0]), 10) + "." +
		strconv.FormatUint(uint64(v[1]), 10) + "." +
		strconv.FormatUint(uint64(v[2]), 10)
}

// BuildHash returns md5(version string) — the value placed in
// devicePairingData.buildHash.
func (v WAVersion) BuildHash() []byte {
	sum := md5.Sum([]byte(v.String()))
	return sum[:]
}

// Browser mirrors Baileys' config.browser tuple: {os, browser, osVersion}.
// The first element becomes DeviceProps.os, the second selects the
// DeviceProps.platformType.
type Browser [3]string

// RegInput carries everything RegistrationPayload needs to build the
// registration ClientPayload. The key material is supplied by the caller
// (generated by internal/keys, or injected from a fixture for testing).
type RegInput struct {
	RegistrationID  uint32
	IdentityPub     [32]byte
	SignedPreKeyID  uint32
	SignedPreKeyPub [32]byte
	SignedPreKeySig [64]byte

	Version     WAVersion
	Browser     Browser
	CountryCode string // localeCountryIso31661Alpha2, e.g. "US"
	SyncFull    bool   // requireFullSync / config.syncFullHistory

	// Device fingerprint fields that flow into the UserAgent submessage. When a
	// field is the zero value the builder substitutes the historical Baileys
	// default (see uaOrDefault) so an empty RegInput reproduces the original
	// hardcoded payload byte-for-byte. internal/control.DeviceProfile fills these
	// to vary the fingerprint per instance.
	OSVersion     string // UserAgent.osVersion (default "0.1")
	Device        string // UserAgent.device (default "Desktop")
	OSBuildNumber string // UserAgent.osBuildNumber (default "0.1")
	LocaleLang    string // UserAgent.localeLanguageIso6391 (default "en")
	MCC           string // UserAgent.mcc (default "000")
	MNC           string // UserAgent.mnc (default "000")
}

// keyBundleType is Baileys' KEY_BUNDLE_TYPE = Buffer.from([5]).
var keyBundleType = []byte{5}

// encodeBigEndian writes v into a big-endian byte slice of length n,
// mirroring Baileys' encodeBigEndian(value, size).
func encodeBigEndian(v uint32, n int) []byte {
	b := make([]byte, n)
	r := v
	for i := n - 1; i >= 0; i-- {
		b[i] = byte(r & 0xff)
		r >>= 8
	}
	return b
}

// platformType maps the browser name to the DeviceProps platform enum,
// falling back to CHROME (matching Baileys' getPlatformType).
func platformType(browser string) DeviceProps_PlatformType {
	switch up := upper(browser); up {
	case "CHROME":
		return DeviceProps_CHROME
	case "FIREFOX":
		return DeviceProps_FIREFOX
	case "IE":
		return DeviceProps_IE
	case "OPERA":
		return DeviceProps_OPERA
	case "SAFARI":
		return DeviceProps_SAFARI
	case "EDGE":
		return DeviceProps_EDGE
	case "DESKTOP":
		return DeviceProps_DESKTOP
	default:
		return DeviceProps_CHROME
	}
}

func upper(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'a' && c <= 'z' {
			b[i] = c - 32
		}
	}
	return string(b)
}

// deviceProps builds the serialized DeviceProps blob (devicePairingData.deviceProps),
// matching Baileys' `companion` object exactly.
func deviceProps(in RegInput) ([]byte, error) {
	dp := &DeviceProps{
		Os:              proto.String(in.Browser[0]),
		PlatformType:    platformType(in.Browser[1]).Enum(),
		RequireFullSync: proto.Bool(in.SyncFull),
		HistorySyncConfig: &DeviceProps_HistorySyncConfig{
			StorageQuotaMb:                           proto.Uint32(10240),
			InlineInitialPayloadInE2EeMsg:            proto.Bool(true),
			SupportCallLogHistory:                    proto.Bool(false),
			SupportBotUserAgentChatHistory:           proto.Bool(true),
			SupportCagReactionsAndPolls:              proto.Bool(true),
			SupportBizHostedMsg:                      proto.Bool(true),
			SupportRecentSyncChunkMessageCountTuning: proto.Bool(true),
			SupportHostedGroupMsg:                    proto.Bool(true),
			SupportFbidBotChatHistory:                proto.Bool(true),
			SupportMessageAssociation:                proto.Bool(true),
			SupportGroupHistory:                      proto.Bool(false),
		},
		Version: &DeviceProps_AppVersion{
			Primary:   proto.Uint32(10),
			Secondary: proto.Uint32(15),
			Tertiary:  proto.Uint32(7),
		},
	}
	return proto.Marshal(dp)
}

// uaOrDefault returns v unless it is empty, in which case it returns def. This
// keeps a zero-valued RegInput (or one lacking device fingerprint fields)
// producing the original hardcoded UserAgent, preserving the captured fixture.
func uaOrDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// userAgent builds the UserAgent submessage shared by registration and login
// payloads (Baileys' getUserAgent). The device fingerprint fields fall back to
// the historical Baileys defaults when unset (see uaOrDefault), so an unmodified
// RegInput reproduces the original payload exactly.
func userAgent(in RegInput) *ClientPayload_UserAgent {
	return &ClientPayload_UserAgent{
		AppVersion: &ClientPayload_UserAgent_AppVersion{
			Primary:   proto.Uint32(in.Version[0]),
			Secondary: proto.Uint32(in.Version[1]),
			Tertiary:  proto.Uint32(in.Version[2]),
		},
		Platform:                    ClientPayload_UserAgent_WEB.Enum(),
		ReleaseChannel:              ClientPayload_UserAgent_RELEASE.Enum(),
		OsVersion:                   proto.String(uaOrDefault(in.OSVersion, "0.1")),
		Device:                      proto.String(uaOrDefault(in.Device, "Desktop")),
		OsBuildNumber:               proto.String(uaOrDefault(in.OSBuildNumber, "0.1")),
		LocaleLanguageIso6391:       proto.String(uaOrDefault(in.LocaleLang, "en")),
		Mnc:                         proto.String(uaOrDefault(in.MNC, "000")),
		Mcc:                         proto.String(uaOrDefault(in.MCC, "000")),
		LocaleCountryIso31661Alpha2: proto.String(in.CountryCode),
	}
}

// RegistrationPayload builds the registration ClientPayload, byte-for-byte
// equivalent (modulo protobuf field ordering) to Baileys'
// generateRegistrationNode.
func RegistrationPayload(in RegInput) (*ClientPayload, error) {
	dp, err := deviceProps(in)
	if err != nil {
		return nil, err
	}
	identity := in.IdentityPub
	skVal := in.SignedPreKeyPub
	skSig := in.SignedPreKeySig
	return &ClientPayload{
		ConnectType:   ClientPayload_WIFI_UNKNOWN.Enum(),
		ConnectReason: ClientPayload_USER_ACTIVATED.Enum(),
		UserAgent:     userAgent(in),
		WebInfo: &ClientPayload_WebInfo{
			WebSubPlatform: ClientPayload_WebInfo_WEB_BROWSER.Enum(),
		},
		Passive: proto.Bool(false),
		Pull:    proto.Bool(false),
		DevicePairingData: &ClientPayload_DevicePairingRegistrationData{
			BuildHash:   in.Version.BuildHash(),
			DeviceProps: dp,
			ERegid:      encodeBigEndian(in.RegistrationID, 4),
			EKeytype:    keyBundleType,
			EIdent:      identity[:],
			ESkeyId:     encodeBigEndian(in.SignedPreKeyID, 3),
			ESkeyVal:    skVal[:],
			ESkeySig:    skSig[:],
		},
	}, nil
}

// LoginInput carries the fields needed to build a resume/login ClientPayload.
type LoginInput struct {
	Username uint64 // numeric user part of the JID
	Device   uint32 // device part of the JID

	Version     WAVersion
	CountryCode string

	// Device fingerprint fields (same semantics as RegInput); empty -> default.
	OSVersion     string
	DeviceName    string
	OSBuildNumber string
	LocaleLang    string
	MCC           string
	MNC           string
}

// LoginPayload builds the resume ClientPayload (Baileys' generateLoginNode):
// passive=true, pull=true, username+device set, no devicePairingData.
func LoginPayload(in LoginInput) *ClientPayload {
	ua := userAgent(RegInput{
		Version:       in.Version,
		CountryCode:   in.CountryCode,
		OSVersion:     in.OSVersion,
		Device:        in.DeviceName,
		OSBuildNumber: in.OSBuildNumber,
		LocaleLang:    in.LocaleLang,
		MCC:           in.MCC,
		MNC:           in.MNC,
	})
	return &ClientPayload{
		ConnectType:   ClientPayload_WIFI_UNKNOWN.Enum(),
		ConnectReason: ClientPayload_USER_ACTIVATED.Enum(),
		UserAgent:     ua,
		WebInfo: &ClientPayload_WebInfo{
			WebSubPlatform: ClientPayload_WebInfo_WEB_BROWSER.Enum(),
		},
		Passive:       proto.Bool(true),
		Pull:          proto.Bool(true),
		Username:      proto.Uint64(in.Username),
		Device:        proto.Uint32(in.Device),
		LidDbMigrated: proto.Bool(false),
	}
}
